Ice-Cream-master/Ice_Cream/Models/Cart.cs
using System.Collections.Generic;
using System.Linq;


namespace Ice_Cream.Models
{
    public class Cart
    {
        public List<CartLine> Lines { get; set; } = new List<CartLine>();

        public void AddItem(Product product, int id)
        {

            CartLine line = Lines.Where(p => p.Product.ProductID == product.ProductID).FirstOrDefault();

            if (line == null)
            {
                Lines.Add(new CartLine
                {
                    Product = product,
                    ID = product.ProductID,
                });
            }
        }
        public void RemoveById(long productid)
        {
            Lines.RemoveAll(p => p.Product.ProductID == productid);
        }

        public decimal ComputeTotalValue()
            => Lines.Sum(e => e.Product.Price * 1);
        public void Clear() => Lines.Clear();

    }
    public class CartLine
    {
        public long ID { get; set; }
        public Product Product { get; set; }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;


namespace Ice_Cream.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;


namespace Ice_Cream.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ice_Cream.Models;
using Ice_Cream.Models.ViewModels;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Ice_Cream.Controllers
{
    public class RecipeController : Controller
    {

        //return view
        public IActionResult Index()
        {
            return View();
        }

        // phân trang
        private IStoreRepository repository;
        public RecipeController(IStoreRepository repo)
        {
            repository = repo;
        }
        public int PageSize = 3;
        public ViewResult CateRecipe(string category, int productPage = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Where(
                        e => e.Category == category).Count()
                }
            });
        // page detail
        public IActionResult Detail(int id)
        {
            return View(
                new Detail
                {
                    Products = repository.Products.Where(p => p.ProductID == id)
                }
                );
        }


        // xử lí ngoại lệ
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
    }
}

Ice-Cream-master/Ice_Cream/Pages/Cart.cshtml.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Ice_Cream.Infrastructure;
using Ice_Cream.Models;

namespace Ice_Cream.Pages
{
    public class CartModel : PageModel
    {
        public Cart Cart { get; set; }
        public string ReturnUrl { get; set; }



        private IStoreRepository repository;


        public CartModel(IStoreRepository repo)
        {
            repository = repo;
        }



        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public IActionResult OnPost(long productId, string returnUrl)
        {
            Product product = repository.Products
                .FirstOrDefault(p => p.ProductID == productId);
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.AddItem(product, 1);
            HttpContext.Session.SetJson("cart", Cart);
            return RedirectToPage(new { returnUrl = returnUrl });
        }
        public IActionResult OnPostRemove(long productId, string returnUrl)
        {
            Product product = repository.Products
           .FirstOrDefault(p => p.ProductID == productId);
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.RemoveById(productId);
            HttpContext.Session.SetJson("cart", Cart);
            return RedirectToPage(new { returnUrl = returnUrl });
        }


        public IActionResult OnPostClear(string returnUrl)
        {

            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
            Cart.Clear();
            return RedirectToPage(new { returnUrl = returnUrl });
        }
    }
}

Ice-Cream-master/Ice_Cream/Pages/Checkout.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ice_Cream.Infrastructure;
using Ice_Cream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ice_Cream.Pages
{
    public class CheckoutModel : PageModel
    {
        //create method
        private StoreDbContext db;
        public Cart Cart { get; set; }
        [BindProperty]
        public Bill bill { get; set; }
        public string ReturnUrl { get; set; }


        //method
        public void OnGet(string returnUrl)//get info cart
        {
            bill = new Bill();

            ReturnUrl = returnUrl ?? "/";
            Cart = HttpContext.Session.GetJson<Cart>("cart") ?? new Cart();
        }

        public CheckoutModel(StoreDbContext _db)
        {
            db = _db;
        }



        public void OnPost()
        {

            db.Bills.Add(bill);
            db.SaveChanges();
        }
    }
}

Ice-Cream-master/Ice_Cream/Pages/User.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Ice_Cream.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Ice_Cream.Pages
{
    public class UserModel : PageModel
    {
        private StoreDbContext db;

        [BindProperty]
        public Customer customer { get; set; }



        public UserModel(StoreDbContext _db)
        {
            db = _db;
        }

        public void OnGet()
        {
            customer = new Customer();
        }

        public void OnPost()
        {
            db.Customers.Add(customer);
            db.SaveChanges();

        }
    }
}

Ice-Cream-master/Ice_Cream/Pages/Cart.cshtml
@page

@model CartModel






<section class="col-xs-12 col-md-12 mt-4">

    <div class="container">

        <div class="row">
            <h2 class="text-center font-weight-bold mb-4 mt-4 col-xs-12 col-md-12">Shopping Cart</h2>

            @*<div class="basket-module text-center col-xs-12 col-md-12 mb-4">
                    <label for="promo-code" class="mt-2 mb-2">Enter a promotional code</label>
                    <br />
                    <input id="promo-code mt-2 mb-2" type="text" name="promo-code" maxlength="5" class="promo-code-field">
                    <br />
                    <button onclick="getPromoCode()" class="promo-code-cta btn btn-success mt-2 mb-2">Apply</button>
                </div>*@

            <div class="shopping-list col-xs-9 col-md-9">
                <table class="table table-bordered table-striped text-center">
                    <thead>
                        <tr class="text-center p-2">
                            <td style="width: 30%;">Product Image</td>
                            <td style="width: 20%;">Product Name</td>
                            <td style="width: 20%;">Category</td>
                            <td>Price</td>
                            <td class="hide">Update</td>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var line in Model.Cart.Lines)
                        {
                            <form method="post" asp-page-handler="remove" id="@line.ID">
                                <tr class="text-center p-2">
                                    <td class="product-detail">
                                        <img src="@line.Product.Image"
                                             alt="product-image"
                                             class="product-frame">
                                    </td>
                                    <td class="product-description">
                                        <span>@line.Product.Name</span>
                                    </td>
                                    <td class="product-category">
                                        <span>@line.Product.Category</span>
                                    </td>
                                    <td class="product-total">
                                        <span>@line.Product.Price.ToString("c")</span>
                                    </td>
                                    <td>

                                        <button type="submit" class="btn btn-danger">Remove</button>

                                    </td>
                                </tr>
                                <input type="hidden" name="productId" value="@line.ID" />

                            </form>

                        }
                    </tbody>
                </table>
            </div>
            <br />
            <div class="col-md-3 cart-button-position">
                <div class="col-md-3 cart-button">
                    <div>
                        <a asp-page="Checkout" style="width: 90%; height: 50px; padding-top: 10px;" class="btn btn-success">Go to Check out</a>
                    </div><br />
                    <div>
                        <a asp-page="User" style="width: 90%; height: 50px; padding-top: 10px;" class="btn btn-success">Get info</a>
                    </div><br />
                    <div>
                        <a asp-controller="Recipe" asp-action="Index" style="width: 90%; height: 50px; padding-top: 10px;" class="btn btn-primary">Continue Shopping</a>
                    </div>
                </div>
            </div>

            <br />


        </div>
    </div>

</section>

Ice-Cream-master/Ice_Cream/Pages/Checkout.cshtml
@page
@model Ice_Cream.Pages.CheckoutModel
<environment>
    <link rel="stylesheet" href="/css/checkout.css" />
</environment>



<div class="container">
    <div class="row">
        <div class="col-md-7">
            <form method="post" asp-page-handler="checkout">
                <div class="form-group">
                    <select name="CatePayment" asp-for="bill.catePayment" class="form-control">
                        <option value="null" selected="selected">Choose the form of payment</option>
                        <option value="delivery">Payment on delivery</option>
                        <option value="electionic-wallet">Payment through electronic wallet</option>
                        <option value="via-bank-account">Payment via bank account</option>
                        <option value="credit-card">Pay by credit card</option>
                    </select>
                </div>

                <div>

                    <input type="hidden" asp-for="bill.TotalPrice" value="@Model.Cart.ComputeTotalValue()" />
                </div>
            </form>
        </div>


        <div class="summary-checkout col-md-4">
            <button type="submit" class="btn btn-success">Go to Secure Checkout</button>
        </div>


        <div class="title-checkout"><h2>Items in your Bag</h2></div>

        <table class="table" style="background-color:white">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">First</th>
                    <th scope="col">Last</th>
                    <th scope="col">Handle</th>
                </tr>
            </thead>
            @foreach (var line in @Model.Cart.Lines)
            {
                <tbody>
                    <tr>
                        <th scope="row">1</th>
                        <td>@line.Product.Name</td>
                        <td>@line.Product.Category</td>
                        <td>@line.Product.Price.ToString("c")</td>
                    </tr>

                </tbody>
            }
        </table>

        @*<tr>
                <td class="product-description">
                    <span>@line.Product.Name</span>
                </td>
                <td class="product-category">
                    <span>@line.Product.Category</span>
                </td>
                <td class="product-total">
                    <span>@line.Product.Price.ToString("c")</span>
                </td>
            </tr>*@

        <div>
            <div class="btn btn-danger">Total: @Model.Cart.ComputeTotalValue().ToString("c")</div>
        </div>


    </div>
</div>

Ice-Cream-master/Ice_Cream/Pages/User.cshtml
@page
@model Ice_Cream.Pages.UserModel

<environment>
    <link rel="stylesheet" href="/css/user.css" />
</environment>


<div class="container">
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6 information">
            <form method="post">
                <div class="form-group">
                    <label for="name">Name:</label>
                    <input type="text" class="form-control" asp-for="customer.CustomerName" />
                </div>
                <div class="form-group">
                    <label for="birth">Birthday:</label>
                    <input type="date" class="form-control" asp-for="customer.Birthday" />
                </div>
                <div class="form-group">
                    <label for="address">Address:</label>
                    <input type="text" class="form-control" asp-for="customer.Address" />
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <input type="email" class="form-control" asp-for="customer.Email" />
                </div>
                <div class="form-group">
                    <label for="pwd">Phone:</label>
                    <input type="text" class="form-control" asp-for="customer.Phone" />
                </div>
                <div class="submit">
                    <input type="submit" class="btn btn-danger btn-md" value="Save" />
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
</div>

Ice-Cream-master/Ice_Cream/Pages/_CartLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Ice Cream</title>
    <link href="/lib/twitter-bootstrap/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/js/bootstrap.min.js" />

    <link rel="stylesheet" id="mfn-fonts-css" href="https://fonts.googleapis.com/css?family=DM+Sans%3A1%2C300%2C400%2C400italic%2C500%2C700%2C700italic%7CTitan+One%3A1%2C300%2C400%2C400italic%2C500%2C700%2C700italic&amp;ver=5.3.6" type="text/css" media="all">
    <link rel="stylesheet" id="Montserrat-css" href="https://fonts.googleapis.com/css?family=Montserrat%3A400%2C500&amp;ver=5.3.6" type="text/css" media="all">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Aclonica&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Titan+One&display=swap" rel="stylesheet">
    <link href="~/lib/fontawesome-free-5.15.1-web/css/all.css" rel="stylesheet">
    <script defer src="~/lib/fontawesome-free-5.15.1-web/js/all.js"></script>
    <link rel="stylesheet" href="~/css/Cart.css" />
</head>
<body>
    <div style="background:#f9b3cf;">
        <div class="container">
            <div class="top-bar-left">
                <div class="logo">
                    <a href="/#"><span>ICE CREAM</span></a>
                </div>
                <div class="menu-wrapper">
                    <ul class="menu-ul">
                        <li><a asp-controller="Home" asp-action="Index"><span>Home</span></a></li>
                        <li><a asp-controller="Recipe" asp-action="Index"><span style="color:#d41442;font-size:20px">Recipe</span></a></li>
                        <li><a asp-controller="About" asp-action="Index"><span>About</span></a></li>
                        <li><a asp-controller="Contact" asp-action="Index"><span>Contact</span></a></li>
                    </ul>
                </div>
            </div>
            <div class="top-bar-right">
                <div class="login">

                </div>
            </div>
        </div>

    </div>
    <div class="m-1 p-1">
        @RenderBody()
    </div>

    <footer>
        <div class="widgets-wapper">
            <div class="container">
                <div class="columns-footer-one col-6">
                    <h3>HOMEMADE ICE CREAM MADE</h3>
                    <h2>WITH PASSION</h2>
                </div>
                <div class="columns-footer-two col-6">
                    <p>
                        <a href="twitter.com"><i class="fab fa-twitter-square"></i></a>
                        <a href="facebook.com"><i class="fab fa-facebook-square"></i></a>
                        <a href="skype.com"><i class="fab fa-skype"></i></a>
                    </p>
                    <div class="text-contact-footer">
                        <h6>
                            Feel free to contact
                            <span>+84 1892938283</span>
                        </h6>
                    </div>
                </div>
            </div>
        </div>
        <div class="footer-copy">
            <div class="copy-right">
                <span> © 2020 BeIceCream 2 - BeTheme. All Rights Reserved. </span>
                <a target="_blank" href="#">About Us</a>
            </div>
        </div>
    </footer>

</body>
</html>