Ice-Cream-master/Ice_Cream/Models/ViewModels/Detail.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ice_Cream.Models.ViewModels
{
    public class Detail
    {
        public IEnumerable<Product> Products { get; set; }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/AboutController.cs
using Microsoft.AspNetCore.Mvc;


namespace Ice_Cream.Controllers
{
    public class AboutController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;


namespace Ice_Cream.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ice_Cream.Controllers
{
    public class LoginController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public ActionResult SignUp()
        {
            return View();
        }
        public ActionResult PasswordReset()
        {
            return View();
        }
        public ActionResult PasswordChange()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/ProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Ice_Cream.Controllers
{
    public class ProviderController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult All_order()
        {
            return View();
        }

        public IActionResult All_product()
        {
            return View();
        }
        public IActionResult Recipe_free()
        {
            return View();
        }
        public IActionResult Recipe_fee()
        {
            return View();
        }
        public IActionResult Recipe_bundle()
        {
            return View();
        }
        public IActionResult Sales()
        {
            return View();
        }
        public IActionResult Bank_account()
        {
            return View();
        }
        public IActionResult Payment()
        {
            return View();
        }
        public IActionResult Sale_analysis()
        {
            return View();
        }
        public IActionResult Effect()
        {
            return View();
        }
        public IActionResult Chat_assitant()
        {
            return View();
        }
        public IActionResult File_shop()
        {
            return View();
        }
        public IActionResult Category_shop()
        {
            return View();
        }
        public IActionResult MyReport()
        {
            return View();
        }
    }
}

Ice-Cream-master/Ice_Cream/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Ice_Cream.Models;
using Ice_Cream.Models.ViewModels;
using System.Diagnostics;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;

namespace Ice_Cream.Controllers
{
    public class RecipeController : Controller
    {

        //return view
        public IActionResult Index()
        {
            return View();
        }

        // phân trang
        private IStoreRepository repository;
        public RecipeController(IStoreRepository repo)
        {
            repository = repo;
        }
        public int PageSize = 3;
        public ViewResult CateRecipe(string category, int productPage = 1)
            => View(new ProductsListViewModel
            {
                Products = repository.Products
                .Where(p => category == null || p.Category == category)
                .OrderBy(p => p.ProductID)
                .Skip((productPage - 1) * PageSize)
                .Take(PageSize),
                PagingInfo = new PagingInfo
                {
                    CurrentPage = productPage,
                    ItemsPerPage = PageSize,
                    TotalItems = category == null ?
                    repository.Products.Count() :
                    repository.Products.Where(
                        e => e.Category == category).Count()
                }
            });
        // page detail
        public IActionResult Detail(int id)
        {
            return View(
                new Detail
                {
                    Products = repository.Products.Where(p => p.ProductID == id)
                }
                );
        }


        // xử lí ngoại lệ
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

       
    }
}

Ice-Cream-master/Ice_Cream/Views/Recipe/CateRecipe.cshtml
@*@model IQueryable<Product>*@
@model ProductsListViewModel

<environment>
    <link rel="stylesheet" href="~/css/recipe.css" />
</environment>
<div style="background:#f9b3cf;">
    <div class="container">
        <div class="top-bar-left">
            <div class="logo">
                <a href="/#"><span>ICE CREAM</span></a>
            </div>
            <div class="menu-wrapper">
                <ul class="menu-ul">
                    <li><a asp-controller="Home" asp-action="Index"><span>Home</span></a></li>
                    <li><a asp-controller="Recipe" asp-action="Index"><span style="color:#d41442;font-size:20px">Recipe</span></a></li>
                    <li><a asp-controller="About" asp-action="Index"><span>About</span></a></li>
                    <li><a asp-controller="Contact" asp-action="Index"><span>Contact</span></a></li>
                </ul>
            </div>
        </div>
        <div class="top-bar-right">
            <div class="login">
                <span></span>
            </div>
        </div>
    </div>

</div>

<div class="image-slide" style="        background-image: url(https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-subheader2.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        height: 500px;
        background-color: #fff5f7;
    ">
    <div>
        <h1 style="font-size: 65px;
    line-height: 65px;
    padding-left: 300px;
    padding-top: 180px;
    color: white;
    font-weight: 600;
     font-family: 'Titan One', Arial, Tahoma, sans-serif;">
            ICE CREAM<br style="color:red" /> RECIPES
        </h1>
    </div>
</div>
<div style="background-color:#fff5f7; padding:100px 0 100px; height:auto">
    <div class="container text-center" style="max-width:1060px;">
        <h1 style="font-size:60px; color:#d41442; margin:0 0 150px; font-family: 'Titan One', Arial, Tahoma, sans-serif;">
            RECIPES FOR YOU
        </h1>
        <div style="max-width:1060px;">
            @foreach (var p in Model.Products)
            {
                <partial name="ProductSummary" model="p" />
            }
        </div>
    </div>
</div>
<div class="button-page text-center" style="background-color:#fff5f7;height:auto; max-width:100%;">
    <div page-model="Model.PagingInfo" page-action="CateRecipe"
         page-classes-enable="true" page-class="btn" page-class-normal="btn-outline-dark"
         page-class-selected="btn-primary" class="btn-group pull-right m-1">
    </div>
</div>

Ice-Cream-master/Ice_Cream/Views/Recipe/Detail.cshtml
@model Detail



<link rel="stylesheet" href="~/css/Detail.css" />
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">

@*chỗ này phần menu*@
<div style="background:#f9b3cf;">
    <div class="container">
        <div class="top-bar-left">
            <div class="logo">
                <a href="/#"><span>ICE CREAM</span></a>
            </div>
            <div class="menu-wrapper">
                <ul class="menu-ul">
                    <li><a asp-controller="Home" asp-action="Index"><span>Home</span></a></li>
                    <li><a asp-controller="Recipe" asp-action="Index"><span style="color:#d41442;font-size:20px">Recipe</span></a></li>
                    <li><a asp-controller="About" asp-action="Index"><span>About</span></a></li>
                    <li><a asp-controller="Contact" asp-action="Index"><span>Contact</span></a></li>
                </ul>
            </div>
        </div>
        <div class="top-bar-right">
            <div class="login">

            </div>
        </div>
    </div>

</div>


<div class="" style="background-image: url(https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-subheader3.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        height: 500px;
        background-color: #fff5f7;
    ">
    <div>
        <h1 style="font-size: 65px;
    line-height: 65px;
    padding-left: 300px;
    padding-top: 180px;
    color: white;
    font-weight: 600;">
            ICE CREAM<br style="color:#d41442" /> RECIPES
        </h1>
    </div>
</div>


<div class="container">
    <div class="card">
        <div class="container-fliud">
            <h2 class="product-title text-center">@Model.Products.First().Name</h2>
            <div class="wrapper row">
                <div class="preview col-md-6">
                    <div class="preview-pic tab-content">
                        <div class="tab-pane active" id="pic-1"><img src="@Model.Products.First().Image" width="400" height="400" /></div>
                    </div>
                </div>
                <div class="details col-md-6">
                    <div class="rating">
                        <div class="stars">
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star checked"></span>
                            <span class="fa fa-star"></span>
                            <span class="fa fa-star"></span>
                        </div>
                        <span class="review-no">41 reviews</span>
                    </div>
                    <p class="vote"><strong>91%</strong> of buyers enjoyed this product! <strong>(87 votes)</strong></p>
                    <h4 class="price">current price: <span>@Model.Products.First().Price.ToString("c")</span></h4>
                    <p class="product-description">@Model.Products.First().Description</p>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <h3>RECIPE</h3>
            <p>@Model.Products.First().Ingredients</p>
            <p>@Model.Products.First().Recipe</p>
            <p><b>Notes:</b>@Model.Products.First().Note</p>
            <div class="action text-center">

                <form method="post" asp-page="/Cart" id="@Model.Products.First().ProductID">

                    <input type="hidden" asp-for="@Model.Products.First().ProductID" />
                    <input type="hidden" name="returnUrl"
                           value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                    <span class="card-text p-1">
                        <br />
                        <br />
                        <br />
                        <hr />
                        <br />
                        <a class="like btn btn-default" type="button" href='/Recipe'>Return Recipe Page</a>
                        <button class="add-to-cart btn btn-default" type="submit">Add to cart</button>
                    </span>
                </form>

            </div>
        </div>            
    </div>
</div>

Ice-Cream-master/Ice_Cream/Views/Recipe/Index.cshtml
@model IEnumerable<string>


<environment>
    <link rel="stylesheet" href="~/css/recipe.css" />
</environment>

@*chỗ này phần menu*@
<div style="background:#f9b3cf;">
    <div class="container">
        <div class="top-bar-left">
            <div class="logo">
                <a href="/#"><span>ICE CREAM</span></a>
            </div>
            <div class="menu-wrapper">
                <ul class="menu-ul">
                    <li><a asp-controller="Home" asp-action="Index"><span>Home</span></a></li>
                    <li><a asp-controller="Recipe" asp-action="Index"><span style="color:#d41442;font-size:20px">Recipe</span></a></li>
                    <li><a asp-controller="About" asp-action="Index"><span>About</span></a></li>
                    <li><a asp-controller="Contact" asp-action="Index"><span>Contact</span></a></li>
                </ul>
            </div>
            @*thêm login, sign up*@
            <div class="login">
                <ul class="menu-login">
                    <li><a asp-controller="Login" asp-action="SignUp" class="btn btn-danger btn-md"><span>Sign up</span></a></li>
                    <li><a asp-controller="Login" asp-action="Index" class="btn btn-danger btn-md"><span>Login</span></a></li>
                </ul>
                <div class="provider">
                    <a asp-controller="Provider" asp-action="Index">Kênh người bán</a>
                </div>
            </div>
        </div>
        <div class="top-bar-right">
            <div class="card" style="float:left">
                <span></span>
            </div>
        </div>
    </div>
</div>

<div style="background-image: url(https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-subheader3.jpg);
        background-repeat: no-repeat;
        background-size: cover;
        height: 500px;
        background-color: #fff5f7;
    ">
    <div>
        <h1 style="font-size: 65px;
    line-height: 65px;
    padding-left: 300px;
    padding-top: 180px;
    color: white;
    font-weight: 600;">
            ICE CREAM<br /> RECIPES
        </h1>
    </div>
    @*Cart*@
    <div class="cart-position">
        <a asp-page="/Cart" class="cart-div"><div class="cart text-center"><i class="fas fa-shopping-cart"></i></div></a>
    </div>
</div>
<div class="text-center col-12 container" style="color: white;background-image:url(https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-sectionbg3.jpg);
                                                    background-color:white;background-repeat:no-repeat;background-position:center; padding:120px 0 50px">
    <div class="col-12 col">
        <h4 style="color:#FF99FF;">CHOOSE</h4>
        <h1 style="margin-bottom:250px;font-size:60px; color:#d41442;">RECIPES</h1>
    </div>
    <div class="col-12 col row">
        <div class="col-1"></div>
        <div class="col-3" style="background-color:#ffb8c9; border-radius:5px; margin-right:30px; margin-left:45px;">
            <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-home-pic1.png" width="230" style="margin:-150px 0 100px;" />
            <h3>FREE</h3>
            <p style="margin: 20px 0 100px;">
                Hãy tìm hiểu các công thức làm kem miễn phí ngay tại đây!
            </p>
            @*sửa*@
            <a asp-action="CateRecipe"
               asp-controller="Recipe"
               asp-route-category="Free"
               asp-route-productPage="1">
                <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-arrow-right.png" style=" max-width: 100%; height: auto; margin-bottom:50px;" width="40" height="40" />
            </a>
            @*sửa*@
        </div>
        <div class="col-3" style="background-color:#efd1a5; border-radius:5px; margin-top:-50px; margin-right:30px;">
            <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-home-pic2.png" width="230" style="margin: -150px 0 100px;" />
            <h3>FEE</h3>
            <p style="margin: 20px 0 150px;">
                Recipes for an extra<br /> fee to watch.
            </p>
            @*sửa*@
            <a asp-action="CateRecipe"
               asp-controller="Recipe"
               asp-route-category="Fee"
               asp-route-productPage="1">
                <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-arrow-right.png" style=" max-width: 100%; height: auto; margin-bottom:50px;" width="40" height="40" />
            </a>
            @*sửa*@
        </div>
        <div class="col-3" style="background-color:#c1e297; border-radius:5px;">
            <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-home-pic3.png" width="230" style="margin:-150px 0 100px;" />
            <h3>BUNDLE</h3>
            <p style="margin: 20px 0 150px;">
                Recipes for subscribers.
            </p>
            @*sửa*@
            <a asp-action="CateRecipe"
               asp-controller="Recipe"
               asp-route-category="Bundle"
               asp-route-productPage="1">
                <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-arrow-right.png" style=" max-width: 100%; height: auto; margin-bottom:50px;" width="40" height="40" />
            </a>
            @*sửa*@
        </div>
        <div class="col-1"></div>
    </div>
</div>

<style>
    h1, h2, h3, h4 {
        font-family: 'Titan One', Arial, Tahoma, sans-serif;
    }

    .image_frame {
        border-color: #f8f8f8;
        margin-bottom: 50px;
    }

        .image_frame.no_border {
            border-width: 0;
        }
</style>

<div style="padding-top: 120px;
padding-bottom: 80px;
background-color: #fff5f7;
background-image: url(https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-sectionbg1.png) ;
background-repeat: no-repeat;
background-size: cover;
height:700px;">
    <div class="text-center">
        <h3 style="color:#ffa5ba; margin-bottom:15px">TRADITION AND LOVE</h3>
        <h2 style="color:#d41442; margin-bottom:30px">HOW IT'S MADE</h2>
    </div>
    <div style="width:35%; float:left;">
        <img src="http://collectionpng.com/images/14250.png" width="250" height="350" style="margin-left:120px;margin-bottom: 45px;">
    </div>
    <div style="margin-top:100px;">
        <h5 style="padding-right:100px;">
            Ice cream is a mixture of milk, cream, sugar, and sometimes other
            ingredients that has been frozen into a soft, creamy delight using special techniques. Ice cream has been a popular
            treat for hundreds of years but has only become commonplace since the widespread use of refrigeration. The exploding
            popularity of ice cream has led to a number of ice-cream variations including frozen custard, frozen yogurt, and even
            non-dairy versions made with ingredients like coconut milk.
        </h5>
    </div>
</div>
<div style="background-color:white; padding-bottom:50px;">
    <img src="https://themes.muffingroup.com/be/icecream2/wp-content/uploads/2019/09/icecream2-home-pic5.jpg" alt="icecream2-home-pic5" title="icecream2-home-pic5" style="width: 100%; height: auto" />
</div>